name: "Continuous Delivery"

on:
  push:
    branches:
      - main # Trigger on push to the main branch (deployment should happen on push to main)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checks out the repository

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2 # Set up Docker Buildx for multi-platform builds

      - name: Build Docker image
        run: |
          docker build -t challenge-latam .  # Builds the Docker image with the tag "challenge-latam"

      - name: Tag and Push Docker image to Google Artifact Registry
        run: |
          # Tag the Docker image to push it to Google Artifact Registry
          docker tag challenge-latam us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/challenge-latam/challenge-latam:latest
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/challenge-latam/challenge-latam:latest

      - name: Deploy to GCP (Cloud Run)
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud run deploy challenge-latam \  # Deploy using your service name
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/challenge-latam/challenge-latam:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated  # Modify based on your deployment preferences
