name: "Continuous Delivery"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2 # Set up Docker Buildx

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-python-app:$GITHUB_SHA .  # Build and tag the image with the commit hash

      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Add your service account key to secrets
          project_id: ${{ secrets.GCP_PROJECT_ID }} # Add your GCP project ID to secrets

      - name: Push Docker image to Google Container Registry
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-python-app:$GITHUB_SHA  # Push the Docker image to GCP Container Registry

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-python-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-python-app:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated  # Adjust region and permissions based on your setup
